import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Deadline Dashboard API
 * Returns upcoming deadlines with risk scoring
 * 
 * GET /api/deadlines/dashboard?userId=uuid&firmView=true
 * 
 * Query params:
 * - userId: Filter by assigned user (optional)
 * - firmView: Show all firm deadlines (default: false)
 * 
 * Returns:
 * {
 *   deadlines: [...],
 *   conflicts: [...],
 *   stats: { total, overdue, dueToday, dueTomorrow, dueThisWeek }
 * }
 */

export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const url = new URL(req.url);
    const userId = url.searchParams.get("userId");
    const firmView = url.searchParams.get("firmView") === "true";

    // Build query
    let query = supabase
      .from("matter_deadlines")
      .select(`
        id,
        deadline_name,
        deadline_type,
        deadline_date,
        status,
        priority,
        is_auto_generated,
        assigned_to,
        matter:cases!matter_deadlines_matter_id_fkey (
          id,
          title
        )
      `)
      .in("status", ["pending", "in_progress"])
      .order("deadline_date", { ascending: true })
      .limit(50);

    // Filter by user if not firm view
    if (!firmView && userId) {
      query = query.eq("assigned_to", userId);
    }

    const { data: deadlines, error: deadlinesError } = await query;

    if (deadlinesError) {
      console.error("Failed to fetch deadlines:", deadlinesError);
      return NextResponse.json(
        { error: "Failed to fetch deadlines" },
        { status: 500 }
      );
    }

    // Fetch conflicts
    const { data: conflicts, error: conflictsError } = await supabase
      .from("deadline_conflicts")
      .select(`
        id,
        conflict_type,
        risk_level,
        deadline_1:matter_deadlines!deadline_conflicts_deadline_1_id_fkey (
          id,
          deadline_name,
          deadline_date,
          matter:cases!matter_deadlines_matter_id_fkey (title)
        ),
        deadline_2:matter_deadlines!deadline_conflicts_deadline_2_id_fkey (
          id,
          deadline_name,
          deadline_date,
          matter:cases!matter_deadlines_matter_id_fkey (title)
        )
      `)
      .eq("resolution_status", "unresolved")
      .limit(10);

    // Calculate stats
    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const nextWeek = new Date(today);
    nextWeek.setDate(nextWeek.getDate() + 7);

    const stats = {
      total: deadlines?.length || 0,
      overdue: deadlines?.filter((d) => new Date(d.deadline_date) < today).length || 0,
      dueToday: deadlines?.filter((d) => {
        const date = new Date(d.deadline_date);
        return date >= today && date < tomorrow;
      }).length || 0,
      dueTomorrow: deadlines?.filter((d) => {
        const date = new Date(d.deadline_date);
        return date >= tomorrow && date < new Date(tomorrow.getTime() + 24 * 60 * 60 * 1000);
      }).length || 0,
      dueThisWeek: deadlines?.filter((d) => {
        const date = new Date(d.deadline_date);
        return date >= today && date < nextWeek;
      }).length || 0,
    };

    // Format response
    const formattedDeadlines = (deadlines || []).map((d: any) => ({
      id: d.id,
      deadlineName: d.deadline_name,
      deadlineType: d.deadline_type,
      deadlineDate: d.deadline_date,
      status: d.status,
      priority: d.priority,
      isAutoGenerated: d.is_auto_generated,
      matterId: d.matter?.id,
      matterTitle: d.matter?.title,
      assignedTo: d.assigned_to,
      assignedToName: null, // TODO: Join with users table
    }));

    const formattedConflicts = (conflicts || []).map((c: any) => ({
      id: c.id,
      conflictType: c.conflict_type,
      riskLevel: c.risk_level,
      deadlines: [
        {
          deadlineName: c.deadline_1?.deadline_name,
          deadlineDate: c.deadline_1?.deadline_date,
          matterTitle: c.deadline_1?.matter?.title,
        },
        {
          deadlineName: c.deadline_2?.deadline_name,
          deadlineDate: c.deadline_2?.deadline_date,
          matterTitle: c.deadline_2?.matter?.title,
        },
      ],
    }));

    return NextResponse.json({
      deadlines: formattedDeadlines,
      conflicts: formattedConflicts,
      stats,
    });
  } catch (error) {
    console.error("Deadline dashboard API error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
