"use client";

import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { 
  Calendar, 
  AlertTriangle, 
  Clock, 
  CheckCircle, 
  XCircle,
  TrendingUp
} from "lucide-react";
import { format, differenceInDays, isPast, isToday, isTomorrow } from "date-fns";
import { cn } from "@/lib/utils/cn";

interface Deadline {
  id: string;
  deadlineName: string;
  deadlineType: string;
  deadlineDate: string;
  matterTitle: string;
  matterId: string;
  assignedToName: string | null;
  status: "pending" | "in_progress" | "completed" | "missed" | "waived";
  priority: "low" | "medium" | "high" | "critical";
  isAutoGenerated: boolean;
}

interface Conflict {
  id: string;
  conflictType: string;
  riskLevel: string;
  deadlines: Array<{
    deadlineName: string;
    matterTitle: string;
    deadlineDate: string;
  }>;
}

export function DeadlineDashboard({ userId, firmView = false }: { userId?: string; firmView?: boolean }) {
  const { data, isLoading } = useQuery({
    queryKey: ["deadline-dashboard", userId, firmView],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (userId) params.set("userId", userId);
      if (firmView) params.set("firmView", "true");

      const res = await fetch(`/api/deadlines/dashboard?${params}`);
      if (!res.ok) throw new Error("Failed to fetch deadlines");
      return res.json();
    },
    refetchInterval: 60000, // Refresh every minute
  });

  const deadlines: Deadline[] = data?.deadlines || [];
  const conflicts: Conflict[] = data?.conflicts || [];
  const stats = data?.stats || {
    total: 0,
    overdue: 0,
    dueToday: 0,
    dueTomorrow: 0,
    dueThisWeek: 0,
  };

  const getDeadlineUrgency = (deadlineDate: string) => {
    const date = new Date(deadlineDate);
    const today = new Date();

    if (isPast(date) && !isToday(date)) {
      return { label: "OVERDUE", variant: "destructive" as const, icon: XCircle };
    }
    if (isToday(date)) {
      return { label: "TODAY", variant: "destructive" as const, icon: AlertTriangle };
    }
    if (isTomorrow(date)) {
      return { label: "TOMORROW", variant: "default" as const, icon: Clock };
    }

    const daysUntil = differenceInDays(date, today);
    if (daysUntil <= 3) {
      return { label: `${daysUntil} DAYS`, variant: "default" as const, icon: Clock };
    }
    if (daysUntil <= 7) {
      return { label: `${daysUntil} DAYS`, variant: "secondary" as const, icon: Calendar };
    }

    return { label: format(date, "dd MMM"), variant: "outline" as const, icon: Calendar };
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "critical":
        return "text-red-600 bg-red-50 border-red-200";
      case "high":
        return "text-orange-600 bg-orange-50 border-orange-200";
      case "medium":
        return "text-blue-600 bg-blue-50 border-blue-200";
      case "low":
        return "text-gray-600 bg-gray-50 border-gray-200";
      default:
        return "text-gray-600 bg-gray-50 border-gray-200";
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-4">
        <div className="grid gap-4 md:grid-cols-4">
          {[1, 2, 3, 4].map((i) => (
            <Card key={i}>
              <CardHeader className="space-y-2 animate-pulse">
                <div className="h-4 bg-gray-200 rounded w-2/3" />
                <div className="h-8 bg-gray-200 rounded w-1/2" />
              </CardHeader>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Stats cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader>
            <CardDescription>Total Deadlines</CardDescription>
            <CardTitle className="text-3xl">{stats.total}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Overdue</CardDescription>
            <CardTitle className="text-3xl text-red-600">{stats.overdue}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Due Today</CardDescription>
            <CardTitle className="text-3xl text-orange-600">{stats.dueToday}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>This Week</CardDescription>
            <CardTitle className="text-3xl text-blue-600">{stats.dueThisWeek}</CardTitle>
          </CardHeader>
        </Card>
      </div>

      {/* Conflicts alert */}
      {conflicts.length > 0 && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Deadline Conflicts Detected</AlertTitle>
          <AlertDescription>
            {conflicts.length} deadline conflict{conflicts.length > 1 ? "s" : ""} require attention.
            <Button variant="link" className="px-2 h-auto font-normal">
              View conflicts →
            </Button>
          </AlertDescription>
        </Alert>
      )}

      {/* Deadlines list */}
      <Card>
        <CardHeader>
          <CardTitle>Upcoming Deadlines</CardTitle>
          <CardDescription>
            {firmView ? "All firm deadlines" : "Your assigned deadlines"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {deadlines.length === 0 ? (
            <div className="text-center py-12 space-y-2">
              <CheckCircle className="w-12 h-12 mx-auto text-green-500" />
              <p className="text-sm text-muted-foreground">No pending deadlines</p>
              <p className="text-xs text-muted-foreground">All caught up!</p>
            </div>
          ) : (
            <div className="space-y-3">
              {deadlines.map((deadline) => {
                const urgency = getDeadlineUrgency(deadline.deadlineDate);
                const UrgencyIcon = urgency.icon;

                return (
                  <div
                    key={deadline.id}
                    className={cn(
                      "flex items-start gap-4 p-4 rounded-lg border",
                      getPriorityColor(deadline.priority)
                    )}
                  >
                    {/* Urgency badge */}
                    <div className="flex-shrink-0">
                      <Badge variant={urgency.variant} className="gap-1.5">
                        <UrgencyIcon className="w-3 h-3" />
                        {urgency.label}
                      </Badge>
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0 space-y-1">
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1">
                          <h4 className="text-sm font-medium">{deadline.deadlineName}</h4>
                          <p className="text-xs text-muted-foreground">
                            {deadline.matterTitle}
                          </p>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge variant="outline" className="text-xs capitalize">
                            {deadline.priority}
                          </Badge>
                          {deadline.isAutoGenerated && (
                            <Badge variant="secondary" className="text-xs">
                              Auto
                            </Badge>
                          )}
                        </div>
                      </div>

                      <div className="flex items-center gap-4 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Calendar className="w-3 h-3" />
                          {format(new Date(deadline.deadlineDate), "dd MMM yyyy, HH:mm")}
                        </span>
                        {deadline.assignedToName && (
                          <span>Assigned to: {deadline.assignedToName}</span>
                        )}
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex-shrink-0">
                      <Button variant="outline" size="sm">
                        View
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
