import type { ReportConfig, ReportType } from "@/types";

export interface PrebuiltReportDefinition {
  id: string;
  name: string;
  description: string;
  type: ReportType;
  category: string;
  config: ReportConfig;
}

const baseDateRange = { preset: "last_30_days" as const };

export const PREBUILT_REPORTS: PrebuiltReportDefinition[] = [
  {
    id: "cases-by-status",
    name: "Active cases by status",
    description: "Snapshot of open matters grouped by workflow status",
    type: "cases",
    category: "Cases",
    config: {
      type: "cases",
      dateRange: baseDateRange,
      fields: ["matter_number", "title", "client_name", "status", "lead_attorney", "age_days"],
      filters: [{ field: "status", operator: "in_list", value: ["OPEN", "PENDING", "ON_HOLD"] }],
      groupBy: "status",
      sort: { field: "age_days", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_cases", seriesField: "status" },
    },
  },
  {
    id: "cases-by-lawyer",
    name: "Cases by lawyer",
    description: "Distribution of caseloads across lead attorneys",
    type: "cases",
    category: "Cases",
    config: {
      type: "cases",
      dateRange: baseDateRange,
      fields: ["matter_number", "title", "client_name", "lead_attorney", "status"],
      filters: [],
      groupBy: "lead_attorney",
      sort: { field: "lead_attorney", direction: "asc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_cases", seriesField: "lead_attorney" },
    },
  },
  {
    id: "cases-by-client",
    name: "Cases by client",
    description: "Top clients by open matter volume",
    type: "cases",
    category: "Cases",
    config: {
      type: "cases",
      dateRange: baseDateRange,
      fields: ["client_name", "title", "status", "lead_attorney"],
      filters: [],
      groupBy: "client_name",
      sort: { field: "client_name", direction: "asc" },
      limit: 50,
      visualization: { chart: "pie", metric: "total_cases", seriesField: "client_name" },
    },
  },
  {
    id: "case-aging",
    name: "Case aging",
    description: "Average days open grouped by status",
    type: "cases",
    category: "Cases",
    config: {
      type: "cases",
      dateRange: baseDateRange,
      fields: ["matter_number", "title", "status", "age_days"],
      filters: [],
      groupBy: "status",
      sort: { field: "age_days", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "avg_age" },
    },
  },
  {
    id: "case-win-loss",
    name: "Case win/loss rate",
    description: "Closed matters by outcome proxy",
    type: "cases",
    category: "Cases",
    config: {
      type: "cases",
      dateRange: { preset: "last_90_days" },
      fields: ["matter_number", "title", "status", "closes_on", "lead_attorney"],
      filters: [{ field: "status", operator: "in_list", value: ["CLOSED"] }],
      groupBy: "lead_attorney",
      sort: { field: "closes_on", direction: "desc" },
      limit: 50,
      visualization: { chart: "pie", metric: "total_cases", seriesField: "lead_attorney" },
    },
  },
  {
    id: "time-by-lawyer",
    name: "Time entries by lawyer",
    description: "Billable mix and utilisation per fee earner",
    type: "time",
    category: "Time",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["work_date", "lawyer", "matter_title", "client_name", "hours", "amount", "billable"],
      filters: [],
      groupBy: "lawyer",
      sort: { field: "hours", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_hours", seriesField: "lawyer" },
    },
  },
  {
    id: "time-by-case",
    name: "Time entries by case",
    description: "Hours captured for each matter",
    type: "time",
    category: "Time",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["work_date", "matter_title", "client_name", "hours", "amount", "status"],
      filters: [],
      groupBy: "matter_title",
      sort: { field: "matter_title", direction: "asc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_hours", seriesField: "matter_title" },
    },
  },
  {
    id: "billable-vs-non",
    name: "Billable vs non-billable",
    description: "Breakdown of captured hours",
    type: "time",
    category: "Time",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["work_date", "lawyer", "matter_title", "billable", "hours"],
      filters: [],
      groupBy: "billable",
      sort: { field: "billable", direction: "desc" },
      limit: 50,
      visualization: { chart: "pie", metric: "total_hours", seriesField: "billable" },
    },
  },
  {
    id: "time-by-task",
    name: "Time by task type",
    description: "Activity code utilisation",
    type: "time",
    category: "Time",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["activity_code", "lawyer", "hours", "amount"],
      filters: [],
      groupBy: "activity_code",
      sort: { field: "hours", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_hours", seriesField: "activity_code" },
    },
  },
  {
    id: "avg-hours-per-case",
    name: "Average hours per case",
    description: "Labour intensity per matter",
    type: "time",
    category: "Time",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["matter_title", "hours", "lawyer"],
      filters: [],
      groupBy: "matter_title",
      sort: { field: "hours", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "total_hours" },
    },
  },
  {
    id: "unbilled-time",
    name: "Unbilled time",
    description: "Hours and value awaiting billing",
    type: "billing",
    category: "Billing",
    config: {
      type: "time",
      dateRange: baseDateRange,
      fields: ["work_date", "matter_title", "client_name", "hours", "amount", "status"],
      filters: [{ field: "status", operator: "equals", value: "UNBILLED" }],
      groupBy: "client_name",
      sort: { field: "amount", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_amount", seriesField: "client_name" },
    },
  },
  {
    id: "revenue-by-client",
    name: "Revenue by client",
    description: "Issued invoices per client",
    type: "billing",
    category: "Billing",
    config: {
      type: "billing",
      dateRange: { preset: "last_90_days" },
      fields: ["invoice_number", "client_name", "status", "issue_date", "total_amount"],
      filters: [{ field: "status", operator: "in_list", value: ["SENT", "PARTIALLY_PAID", "PAID"] }],
      groupBy: "client_name",
      sort: { field: "total_amount", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_revenue", seriesField: "client_name" },
    },
  },
  {
    id: "revenue-by-lawyer",
    name: "Revenue by lawyer",
    description: "Matter revenue attributed to lead",
    type: "billing",
    category: "Billing",
    config: {
      type: "billing",
      dateRange: baseDateRange,
      fields: ["invoice_number", "matter_title", "client_name", "total_amount", "status"],
      filters: [],
      groupBy: "matter_title",
      sort: { field: "total_amount", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "total_revenue" },
    },
  },
  {
    id: "outstanding-invoices",
    name: "Outstanding invoices",
    description: "Aged receivables snapshot",
    type: "billing",
    category: "Billing",
    config: {
      type: "billing",
      dateRange: baseDateRange,
      fields: ["invoice_number", "client_name", "issue_date", "due_date", "balance_due", "status"],
      filters: [{ field: "balance_due", operator: "greater_than", value: 0 }],
      groupBy: "status",
      sort: { field: "due_date", direction: "asc" },
      limit: 100,
      visualization: { chart: "bar", metric: "outstanding", seriesField: "status" },
    },
  },
  {
    id: "payment-history",
    name: "Payment history",
    description: "Recently settled invoices",
    type: "billing",
    category: "Billing",
    config: {
      type: "billing",
      dateRange: baseDateRange,
      fields: ["invoice_number", "client_name", "issue_date", "total_amount", "balance_due", "status"],
      filters: [{ field: "status", operator: "equals", value: "PAID" }],
      groupBy: "client_name",
      sort: { field: "issue_date", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "total_revenue" },
    },
  },
  {
    id: "avg-payment-time",
    name: "Average payment time",
    description: "Cycle time from issue to payment",
    type: "billing",
    category: "Billing",
    config: {
      type: "billing",
      dateRange: { preset: "last_90_days" },
      fields: ["invoice_number", "client_name", "issue_date", "due_date", "status"],
      filters: [],
      groupBy: "client_name",
      sort: { field: "issue_date", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "outstanding" },
    },
  },
  {
    id: "documents-by-case",
    name: "Documents by case",
    description: "Matter-specific document inventory",
    type: "documents",
    category: "Documents",
    config: {
      type: "documents",
      dateRange: baseDateRange,
      fields: ["title", "document_type", "matter_title", "client_name", "updated_at"],
      filters: [],
      groupBy: "matter_title",
      sort: { field: "updated_at", direction: "desc" },
      limit: 100,
      visualization: { chart: "bar", metric: "total_documents", seriesField: "matter_title" },
    },
  },
  {
    id: "documents-by-type",
    name: "Documents by type",
    description: "Mix of document templates",
    type: "documents",
    category: "Documents",
    config: {
      type: "documents",
      dateRange: baseDateRange,
      fields: ["title", "document_type", "status", "owner"],
      filters: [],
      groupBy: "document_type",
      sort: { field: "document_type", direction: "asc" },
      limit: 50,
      visualization: { chart: "pie", metric: "total_documents", seriesField: "document_type" },
    },
  },
  {
    id: "storage-by-client",
    name: "Storage usage by client",
    description: "Total MB of artifacts",
    type: "documents",
    category: "Documents",
    config: {
      type: "documents",
      dateRange: baseDateRange,
      fields: ["client_name", "matter_title", "file_size", "updated_at"],
      filters: [],
      groupBy: "client_name",
      sort: { field: "file_size", direction: "desc" },
      limit: 50,
      visualization: { chart: "bar", metric: "storage_mb", seriesField: "client_name" },
    },
  },
  {
    id: "document-activity",
    name: "Document activity",
    description: "Uploads and edits over time",
    type: "documents",
    category: "Documents",
    config: {
      type: "documents",
      dateRange: baseDateRange,
      fields: ["title", "owner", "updated_at", "status"],
      filters: [],
      groupBy: "owner",
      sort: { field: "updated_at", direction: "desc" },
      limit: 50,
      visualization: { chart: "line", metric: "total_documents" },
    },
  },
  {
    id: "login-history",
    name: "Login history",
    description: "Successful vs failed attempts",
    type: "users",
    category: "User activity",
    config: {
      type: "users",
      dateRange: baseDateRange,
      fields: ["event_time", "email", "user_name", "success", "ip_address", "location"],
      filters: [],
      groupBy: "success",
      sort: { field: "event_time", direction: "desc" },
      limit: 100,
      visualization: { chart: "pie", metric: "total_events", seriesField: "success" },
    },
  },
  {
    id: "active-users",
    name: "Active users",
    description: "Users authenticating in last 30 days",
    type: "users",
    category: "User activity",
    config: {
      type: "users",
      dateRange: baseDateRange,
      fields: ["event_time", "email", "user_name", "location", "device"],
      filters: [{ field: "success", operator: "equals", value: "true" as any }],
      groupBy: "location",
      sort: { field: "event_time", direction: "desc" },
      limit: 100,
      visualization: { chart: "bar", metric: "total_events", seriesField: "location" },
    },
  },
  {
    id: "user-activity-by-date",
    name: "User activity by date",
    description: "Heatmap of logins per day",
    type: "users",
    category: "User activity",
    config: {
      type: "users",
      dateRange: baseDateRange,
      fields: ["event_time", "email", "success"],
      filters: [],
      groupBy: "event_time",
      sort: { field: "event_time", direction: "desc" },
      limit: 100,
      visualization: { chart: "line", metric: "total_events" },
    },
  },
  {
    id: "most-active-users",
    name: "Most active users",
    description: "Accounts with the most successful sessions",
    type: "users",
    category: "User activity",
    config: {
      type: "users",
      dateRange: baseDateRange,
      fields: ["user_name", "email", "device", "success"],
      filters: [{ field: "success", operator: "equals", value: "true" as any }],
      groupBy: "user_name",
      sort: { field: "user_name", direction: "asc" },
      limit: 50,
      visualization: { chart: "bar", metric: "total_events", seriesField: "user_name" },
    },
  },
];

export const getPrebuiltReport = (id: string) => {
  const lookup = id.startsWith("prebuilt-") ? id.replace(/^prebuilt-/, "") : id;
  return PREBUILT_REPORTS.find((report) => report.id === lookup || `prebuilt-${report.id}` === id);
};
