BEGIN;
CREATE TYPE data_classification AS ENUM (
    'INTERNAL_ONLY',
    'FIRM_CONFIDENTIAL',
    'CLIENT_VISIBLE',
    'CLIENT_DOWNLOADABLE',
    'RESTRICTED'
);

CREATE TYPE user_status AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'DISABLED');
CREATE TYPE user_type AS ENUM ('STAFF', 'CLIENT');
CREATE TYPE matter_status AS ENUM ('OPEN', 'PENDING', 'ON_HOLD', 'CLOSED');
CREATE TYPE document_status AS ENUM ('DRAFT', 'FINAL', 'ARCHIVED');
CREATE TYPE custody_event_type AS ENUM ('CREATED', 'UPLOADED', 'TRANSFERRED', 'ACCESSED', 'DOWNLOADED', 'PUBLISHED', 'CHECKSUM_VERIFIED');
CREATE TYPE time_entry_status AS ENUM ('UNBILLED', 'INVOICED', 'WRITEOFF');
CREATE TYPE invoice_status AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'VOID');
COMMIT;
