-- Email integrations for AI Time Capture
-- Stores OAuth tokens for Gmail, Outlook, etc.

CREATE TABLE IF NOT EXISTS email_integrations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('gmail', 'outlook')),
  email_address TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  enabled BOOLEAN DEFAULT true,
  last_synced_at TIMESTAMPTZ,
  sync_errors INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, provider, email_address)
);

-- Time suggestions generated by AI
-- Stores suggestions before user approves/rejects
CREATE TABLE IF NOT EXISTS time_suggestions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source TEXT NOT NULL CHECK (source IN ('email', 'calendar', 'document')),
  source_id TEXT NOT NULL, -- External ID (email ID, calendar event ID, etc.)
  source_provider TEXT, -- gmail, outlook, google_calendar, etc.
  work_date DATE NOT NULL,
  suggested_hours DECIMAL(5,2) NOT NULL,
  description TEXT NOT NULL,
  matter_id UUID REFERENCES cases(id) ON DELETE SET NULL,
  client_id UUID REFERENCES clients(id) ON DELETE SET NULL,
  confidence DECIMAL(3,2) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  activity_code TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'edited')),
  raw_data JSONB, -- Store original email/event data
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES auth.users(id),
  time_entry_id UUID REFERENCES time_entries(id), -- Link to created time entry if approved
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, source, source_id)
);

-- Calendar integrations (similar to email)
CREATE TABLE IF NOT EXISTS calendar_integrations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('google', 'outlook')),
  email_address TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  enabled BOOLEAN DEFAULT true,
  last_synced_at TIMESTAMPTZ,
  sync_errors INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, provider, email_address)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_integrations_user_id ON email_integrations(user_id);
CREATE INDEX IF NOT EXISTS idx_email_integrations_enabled ON email_integrations(user_id, enabled);
CREATE INDEX IF NOT EXISTS idx_time_suggestions_user_status ON time_suggestions(user_id, status);
CREATE INDEX IF NOT EXISTS idx_time_suggestions_date ON time_suggestions(work_date);
CREATE INDEX IF NOT EXISTS idx_time_suggestions_matter ON time_suggestions(matter_id);
CREATE INDEX IF NOT EXISTS idx_calendar_integrations_user_id ON calendar_integrations(user_id);

-- Row-level security
ALTER TABLE email_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_integrations ENABLE ROW LEVEL SECURITY;

-- Policies for email_integrations
CREATE POLICY "Users can view their own email integrations"
  ON email_integrations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own email integrations"
  ON email_integrations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own email integrations"
  ON email_integrations FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own email integrations"
  ON email_integrations FOR DELETE
  USING (auth.uid() = user_id);

-- Policies for time_suggestions
CREATE POLICY "Users can view their own time suggestions"
  ON time_suggestions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own time suggestions"
  ON time_suggestions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own time suggestions"
  ON time_suggestions FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own time suggestions"
  ON time_suggestions FOR DELETE
  USING (auth.uid() = user_id);

-- Policies for calendar_integrations
CREATE POLICY "Users can view their own calendar integrations"
  ON calendar_integrations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own calendar integrations"
  ON calendar_integrations FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own calendar integrations"
  ON calendar_integrations FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own calendar integrations"
  ON calendar_integrations FOR DELETE
  USING (auth.uid() = user_id);

-- Function to clean up old rejected suggestions (keep last 30 days)
CREATE OR REPLACE FUNCTION cleanup_old_time_suggestions()
RETURNS void AS $$
BEGIN
  DELETE FROM time_suggestions
  WHERE status = 'rejected'
    AND created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- Comments for documentation
COMMENT ON TABLE email_integrations IS 'OAuth tokens for Gmail and Outlook email integrations';
COMMENT ON TABLE time_suggestions IS 'AI-generated time entry suggestions from emails, calendar, and documents';
COMMENT ON TABLE calendar_integrations IS 'OAuth tokens for Google Calendar and Outlook Calendar integrations';
